### ISSUE TITLE
Link to compiled apk download

### ISSUE THREAD

**Issue by elsondione** [alxrm/Timecon#2]
Great job

What link to apk compiled download?

**Comment by alxrm** [comment]
Well, you can install one by yourself:

1) Pull the code by running this in terminal:
```git clone https://github.com/alxrm/animated-clock-icon.git```
2) Open the root of the project:
```cd animated-clock-icon```
3) Connect your device via adb and install:
```./gradlew installDebug```
4) If you need the specifically the file, then jump to the directory, where your apk will be generated:
```cd ./app/build/outputs/apk```

Hope this helps 👍 

Anyway I'll consider adding prebuilt apk, so you can just launch an example on your device, thanks for the idea

Closing this issue, since it's not really a problem with the library itself
